#!/bin/bash
#expects a dir location where the backup files are stored

stow -t ~ dircolors
stow -t ~ tmux
stow -t ~ vim
stow -t ~ fonts
stow -t ~ gtk-3.0
stow -t ~ ranger
stow -t ~ gitconfig
stow -t ~ myscripts
stow -t ~ latexmk
stow -t ~ freemind
stow -t ~ mlterm
stow -t ~ zathura
stow -t ~ background
stow -t ~ mpv
#stow -t ~ bash-env

echo "Done"
