#!/bin/bash
#expects a dir location where the backup files are stored

#set -e 

stow -t ~ dircolors
stow -t ~ tmux
stow -t ~ fonts
#stow -t ~ gtk-3.0
stow -t ~ ranger
stow -t ~ gitconfig
stow -t ~ myscripts
stow -t ~ latexmk
stow -t ~ freemind
stow -t ~ mlterm
stow -t ~ zathura
stow -t ~ background
stow -t ~ mpv
stow -t ~ feh
stow -t ~ -d  intellij -S ideavim
stow -t ~ ctags
stow -t ~ tig
stow -t ~ tldr
stow -t ~ notes
stow -t ~ urxvt
stow -t ~ vim
stow -t ~ kitty
stow -t ~ mycli
stow -t ~ karabiner
stow -t ~ run-or-raise
stow -t ~ bat 
stow -t ~ nvim 

#set extentions for urxvt
mkdir -p ~/.urxvt/ext
curl -s https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size > ~/.urxvt/ext/font-size
curl -s https://raw.githubusercontent.com/muennich/urxvt-perls/master/keyboard-select > ~/.urxvt/ext/keyboard-select

#set mlterm vaafont file
if [ ! -f ~/.mlterm/vaafont ]; then
    ln -s ~/.mlterm/vaafont.template ~/.mlterm/vaafont
fi

#shell
stow -t ~ shell
grep "mybashrc" ~/.bashrc > /dev/null 2>&1 
exists=$?
if [ "$exists" -ne 0 ]; then
    echo "source ~/.mybashrc" >> ~/.bashrc
fi

read -p "Do you want Vim Plug? " -n 1 -r
echo    
if [[ $REPLY =~ ^[Yy]$ ]]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo "Done"
