execute pathogen#infect()

"---------------------------------------------------------
"                    Themes                    
"---------------------------------------------------------

"current themes installed
"desertink molokai gruvbox hybrid

" gruvbox
"let g:gruvbox_italic=1
"let g:gruvbox_termcolors=256
"let g:gruvbox_bold=1
"colorscheme gruvbox

" Desert theme
"colorscheme desertink 
"highlight NonText ctermfg=59 ctermbg=NONE cterm=NONE guifg=#414e58 guibg=#232c31 gui=NONE

" hybrid
"let g:hybrid_custom_term_colors = 1
"let g:hybrid_reduced_contrast = 0
"colorscheme hybrid

"---------------------------------------------------------
"                    Visual Changes                    
"---------------------------------------------------------

" colors
set t_Co=256
set background=light

"highlight colo
highlight Visual ctermfg=NONE ctermbg=yellow  cterm=NONE guifg=white guibg=green gui=none

"mode indicator
set showmode
"set noshowmode

" Add a bit extra margin to the left
set foldcolumn=0

"mode indicator color
highlight ModeMsg ctermbg=DARKRED ctermfg=WHITE

" show commands
set showcmd
"delay on escape
set timeoutlen=1000 ttimeoutlen=0

""status bar
"set laststatus=2 
"set statusline+=%0*\ %02n\ \|                              "buffernr
""set statusline+=[%{expand('%:h')}/]                       "parent folder
"set statusline+=%0*\ %t\ \|                                "file name
""set statusline+=%0*\ %<%h\                                "File+path
""set statusline+=%0*\ %<%t\                                "File+path
""set statusline+=%0*\ %y\                                  "FileType
""set statusline+=%0*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
""set statusline+=%0*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
""set statusline+=%0*\ %{&ff}\                              "FileFormat (dos/unix..) 
""set statusline+=%0*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
"set statusline+=%0*\ %=\|\ col:%03c\ \|                    "Colnr
"set statusline+=%0*\ \ %m%r%w\ %P\ \                       "Modified? Readonly? Top/bot.


"change cursor color base on the mode
"if &term =~ "xterm\\|rxvt"
"  " use an orange cursor in insert mode
"  let &t_SI = "\<Esc>]12;red\x7"
"  " use a red cursor otherwise
"  let &t_EI = "\<Esc>]12;orange\x7"
"  silent !echo -ne "\033]12;red\007"
"  " reset cursor when vim exits
"  autocmd VimLeave * silent !echo -ne "\033]112\007"
"  " use \003]12;gray\007 for gnome-terminal and rxvt up to version 9.21
"endif

""change cursor shape based on mode
""http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
"if has("autocmd")
"  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[2 q"' | redraw!
"  au InsertEnter,InsertChange *
"    \ if v:insertmode == 'i' | 
"    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
"    \ elseif v:insertmode == 'r' |
"    \   silent execute '!echo -ne "\e[4 q"' | redraw! |
"    \ endif
"  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
"endif
"---------------------------------------------------------
"                    Encryption                    
"---------------------------------------------------------

" blowfish2 was introduced in 7.4.399
if v:version > 74399
	" encryption
	set cryptmethod=blowfish2
endif

"---------------------------------------------------------
"                    Misc                    
"---------------------------------------------------------

" syntax highlighting
if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" Enable filetype plugins
filetype plugin on
filetype indent on

" show partial lines 
set display=lastline

"backspace to delete
set backspace=indent,eol,start

"fix Ctrl U. 
inoremap <C-U> <C-G>u<C-U>

" Line numbers
set relativenumber
set number

" Set to auto read when a file is changed from the outside
set autoread

" auto ident
set autoindent	
set copyindent "copy the identation from the previous line

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases 
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch 

" Show matching brackets when text indicator is over them
"set showmatch 
" How many tenths of a second to blink when matching brackets
" set mat=2

" Be smart when using tabs ;)
set smarttab

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

" clipboard
set clipboard=unnamedplus
set guitablabel=%N/\ %t\ %M

" not to break on words
set formatoptions=1
set linebreak

"---------------------------------------------------------
"                    Motions                    
"---------------------------------------------------------

"enter normal mode
imap jj <Esc>

" disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" fixing up moving line by line in the paragraph
"nnoremap j gj
"nnoremap k gk
"vnoremap j gj
"vnoremap k gk

" Keep search matches in the middle of the window.
"nnoremap n nzzzv
"nnoremap N Nzzzv

"---------------------------------------------------------
"                    Plugins                    
"---------------------------------------------------------

"" enable hard core mode
let g:hardtime_default_on = 1

"nerdtree
map <C-n> :NERDTreeToggle<CR>

"conoline
let g:conoline_auto_enable = 0
"let g:conoline_color_insert_light = 'ctermbg=black ctermfg=white'
"let g:conoline_color_normal_light = 'ctermbg=black ctermfg=white'

"---------------------------------------------------------
"                    Leader                     
"---------------------------------------------------------

" leader commands
let mapleader = "\<Space>"

" redraw screen
nmap <silent> <leader>r :redraw!<CR>

" reload .vimrc
nmap <leader>z :so ~/.vimrc<CR>

" Disable highlight when <leader><h> is pressed
nmap <silent> <leader>h :nohl<CR>

" leader save
nmap <silent> <leader>s :w<CR>

"---------------------------------------------------------
"                    Leader Buffer Management                     
"---------------------------------------------------------

"vim buffer management
set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>

" Mappings to access buffers (don't use "\p" because a
" " delay before pressing "p" would accidentally paste).
" " \l       : list buffers
" " \i \o \g : go back/forward/last-used
" " \1 \2 \3 : go to buffer 1/2/3 etc
 nnoremap <Leader>l :buffers<CR>:b<Space>
 "nnoremap <Leader>l :ls<CR>
 nnoremap <Leader>i :bp<CR>
 nnoremap <Leader>o :bn<CR>
 nnoremap <Leader>g :e#<CR>
 nnoremap <Leader>1 :1b<CR>
 nnoremap <Leader>2 :2b<CR>
 nnoremap <Leader>3 :3b<CR>
 nnoremap <Leader>4 :4b<CR>
 nnoremap <Leader>5 :5b<CR>
 nnoremap <Leader>6 :6b<CR>
 nnoremap <Leader>7 :7b<CR>
 nnoremap <Leader>8 :8b<CR>
 nnoremap <Leader>9 :9b<CR>
 nnoremap <Leader>0 :10b<CR>
 "set autowriteall
 set confirm
 " ignore unsaved files while switching buffers
 "set hidden

 
"---------------------------------------------------------
"                    Spell Check & Correct                     
"                    Auto Correct                     
"---------------------------------------------------------
" spell checking
"set spell spelllang=en_us
"setlocal spell spelllang=en_us
autocmd BufRead *.tex setlocal spell spelllang=en_us
nmap <silent> <leader>c :set spell!<CR>


" Auto correct mistakes
iab filesystem file system
