#!/bin/bash

if [[ "$1" == "up" ]]; then
	gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method  org.gnome.SettingsDaemon.Power.Screen.StepUp &> /dev/null
elif  [[ "$1" == "down" ]]; then
	gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method  org.gnome.SettingsDaemon.Power.Screen.StepDown &> /dev/null
else
	gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.freedesktop.DBus.Properties.Set org.gnome.SettingsDaemon.Power.Screen Brightness "<int32 $1>" &> /dev/null
fi

curval=$(gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.freedesktop.DBus.Properties.Get org.gnome.SettingsDaemon.Power.Screen Brightness | grep -o [0-9]*)

pkill zenity
message="Current brightness level is $curval"
#timeout 1 zenity --scale --text "$message" --title "$message" --min-value 0 --max-value 100 --value $curval

timeout 1 zenity --info  --text "<span size=\"large\">Brightness</span>\n<span size=\"xx-large\"><b>$curval%</b></span>" --title "$message" --ellipsize 
#--width=80 --height=40
