#!/bin/bash

delta=40
# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.
h=false
j=false
k=false
l=false
while getopts "hjkld:" opt; do
    case "$opt" in
    d)  delta=$OPTARG
    	;;
    h)  h=true
        ;;
    j)  j=true
        ;;
    k)  k=true
        ;;
    l)  l=true
        ;;
    *)
        echo "There is no help." 
        exit 0
        ;;
    esac
done


if [ "$h" = true ]; then
	xdotool mousemove_relative --sync -- -$delta 0
fi

if [ "$j" = true ]; then
	xdotool mousemove_relative --sync -- 0 $delta
fi

if [ "$k" = true ]; then
	xdotool mousemove_relative --sync -- 0 -$delta
fi

if [ "$l" = true ]; then
	xdotool mousemove_relative --sync -- $delta 0 
fi
