#!/bin/bash
#xclip -selection primary -i ~/file
#xclip -selection clipboard -i ~/file

sleep 1
text=$(cat ~/file)
xdotool type --clearmodifiers "$text"
#echo -e "\b"
#xdotool type --clearmodifiers --file  ~/file
