#!/bin/bash
#expects a dir location where the backup files are stored

SRC=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

BACKUP_DIR=$1

if [ -z "$BACKUP_DIR" ]; then
	date=`date +'%B-%d-Time-%H-%M'`
	BACKUP_DIR=~
	BACKUP_DIR="$BACKUP_DIR/dotfiles-$date.bak"
	mkdir -p $BACKUP_DIR
	echo "Backup Dir is: $BACKUP_DIR" 
fi

echo "Installing Xinitrc"
mv ~/.xinitrc $BACKUP_DIR
ln -s $SRC/xinitrc ~/.xinitrc
