#!/bin/bash
#expects a dir location where the backup files are stored

SRC=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


BACKUP_DIR=$1

if [ -z "$BACKUP_DIR" ]; then
	date=`date +'%B-%d-Time-%H-%M'`
	BACKUP_DIR=~
	BACKUP_DIR="$BACKUP_DIR/dotfiles-$date.bak"
	mkdir -p $BACKUP_DIR
	echo "Backup Dir is: $BACKUP_DIR" 
fi


echo "Installing Bash config "
script_names=("alias.sh" "bash-settings.sh" "paths.sh" "tmux-auto-start.sh")
for script_name in "${script_names[@]}"
do
	grep "$script_name" ~/.bashrc > /dev/null 2>&1 
	exists=$?
	if [ "$exists" -ne 0 ]; then
		echo "Installing $script_name "
		cp ~/.bashrc $BACKUP_DIR
		echo "source $SRC/$script_name" >> ~/.bashrc
	#else
	#	echo "Already installed"
	fi
done

mv ~/.inputrc $BACKUP_DIR
ln -s $SRC/inputrc ~/.inputrc
