#!/bin/bash
#expects a dir location where the backup files are stored

SRC=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


BACKUP_DIR=$1

if [ -z "$BACKUP_DIR" ]; then
	date=`date +'%B-%d-Time-%H-%M'`
	BACKUP_DIR=~
	BACKUP_DIR="$BACKUP_DIR/dotfiles-$date.bak"
	mkdir -p $BACKUP_DIR
	echo "Backup Dir is: $BACKUP_DIR" 
fi


script_names=("alias.sh" "bash-settings.sh" "paths.sh" "tmux-auto-start.sh")
for script_name in "${script_names[@]}"
do
	grep "$script_name" ~/.bashrc
	exists=$?
	if [ "$exists" -eq 0 ]; then
		echo "$script_name is already installed in .bashrc "
	else
		echo "Installing $script_name "
		cp ~/.bashrc $BACKUP_DIR
		echo "source $SRC/$script_name" >> ~/.bashrc
	fi
done

echo "Installing Inputrc "
mv ~/.inputrc $BACKUP_DIR
ln -s $SRC/inputrc ~/.inputrc
