#!/bin/bash
export LIBNDBPATH=/home/salman/program_files/clusterj

mvn $@ install -Dmaven.test.skip=true -f ~/code/hopg/hops-metadata-dal/pom.xml

mvn $@ install -Dmaven.test.skip=true -f ~/code/hopg/hops-metadata-dal-impl-ndb/pom.xml

mvn $@ install -Dmaven.test.skip=true generate-sources -Pndb -f ~/code/hopg/hops/pom.xml

#temporarily change pwd
cd ~/code/hopg/hops && mvn test-compile

